### ISSUE TITLE
Getting endless items from plants

### ISSUE THREAD

**Issue by IceMage144** [uspgamedev/lasagna#10]
When interacting with any plant, excluding fleece, (including kepala) you can get endless items while the dying animation is playing.

**Comment by OrenjiAkira** [comment]
I think @kazuo256 fixed this already. Check the lastest version and tell us if this is still happening.

**Comment by IceMage144** [comment]
He tried to fix this at kepala, but the other plants also have this bug. And yes, I'm running the latest version and kepala's bug doesn't seem to be fixed.
